import { DriverRow, DriverStatus } from './types';

export const truckStateStyles: Record<DriverRow['truckState'], string> = {
  active: 'bg-teal-600',
  idle: 'bg-slate-400',
  break: 'bg-blue-400',
};

export const driverStatusTone: Record<
  DriverStatus,
  'success' | 'neutral' | 'info'
> = {
  Break: 'info',
  'Off Duty': 'neutral',
  'On Duty': 'success',
};

export const drivers: DriverRow[] = [
  {
    id: 'DR-1034',
    name: 'John Smith',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1042',
    truckState: 'active',
    currentLoad: 'Load #LD-78291',
    eta: { time: '14:30', state: 'On time' },
  },
  {
    id: 'DR-1021',
    name: 'Maria Johnson',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    status: 'Off Duty',
    truck: 'Truck TR-1009',
    truckState: 'idle',
    currentLoad: null,
    eta: { time: null },
  },
  {
    id: 'DR-1045',
    name: 'Robert Brown',
    avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1055',
    truckState: 'active',
    currentLoad: 'Load #LD-10456',
    eta: { time: '09:45', state: 'Delayed' },
  },
  {
    id: 'DR-1018',
    name: 'Sarah Davis',
    avatarUrl: 'https://randomuser.me/api/portraits/men/52.jpg',
    status: 'Break',
    truck: 'Truck TR-1022',
    truckState: 'break',
    currentLoad: null,
    eta: { time: '11:15' },
  },
  {
    id: 'DR-1007',
    name: 'Michael Wilson',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1066',
    truckState: 'active',
    currentLoad: 'Load #LD-2156',
    eta: { time: '16:20', state: 'On time' },
  },
  {
    id: 'DR-1032',
    name: 'Emily Taylor',
    avatarUrl: 'https://randomuser.me/api/portraits/women/65.jpg',
    status: 'Off Duty',
    truck: 'Truck TR-1011',
    truckState: 'active',
    currentLoad: null,
    eta: { time: null },
  },
  {
    id: 'DR-1051',
    name: 'David Lee',
    avatarUrl: 'https://randomuser.me/api/portraits/men/22.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1088',
    truckState: 'active',
    currentLoad: 'Load #LD-9901',
    eta: { time: '17:05', state: 'Delayed' },
  },
  {
    id: 'DR-1012',
    name: 'Jessica Martinez',
    avatarUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
    status: 'Off Duty',
    truck: 'Truck TR-1033',
    truckState: 'idle',
    currentLoad: null,
    eta: { time: null },
  },
  {
    id: 'DR-1063',
    name: 'Anthony Clark',
    avatarUrl: 'https://randomuser.me/api/portraits/men/41.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1094',
    truckState: 'active',
    currentLoad: 'Load #LD-44821',
    eta: { time: '12:40', state: 'On time' },
  },
  {
    id: 'DR-1074',
    name: 'Olivia Anderson',
    avatarUrl: 'https://randomuser.me/api/portraits/women/29.jpg',
    status: 'Break',
    truck: 'Truck TR-1077',
    truckState: 'break',
    currentLoad: 'Load #LD-33108',
    eta: { time: '13:10' },
  },
  {
    id: 'DR-1082',
    name: 'Daniel Thompson',
    avatarUrl: 'https://randomuser.me/api/portraits/men/58.jpg',
    status: 'Off Duty',
    truck: 'Truck TR-1102',
    truckState: 'idle',
    currentLoad: null,
    eta: { time: null },
  },
  {
    id: 'DR-1096',
    name: 'Sophia Garcia',
    avatarUrl: 'https://randomuser.me/api/portraits/women/23.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1115',
    truckState: 'active',
    currentLoad: 'Load #LD-67234',
    eta: { time: '18:25', state: 'Delayed' },
  },
  {
    id: 'DR-1108',
    name: 'James Robinson',
    avatarUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1120',
    truckState: 'active',
    currentLoad: 'Load #LD-90517',
    eta: { time: '15:50', state: 'On time' },
  },
  {
    id: 'DR-1119',
    name: 'Ava Nguyen',
    avatarUrl: 'https://randomuser.me/api/portraits/women/36.jpg',
    status: 'Off Duty',
    truck: 'Truck TR-1081',
    truckState: 'idle',
    currentLoad: null,
    eta: { time: null },
  },
  {
    id: 'DR-1127',
    name: 'Christopher Hall',
    avatarUrl: 'https://randomuser.me/api/portraits/men/67.jpg',
    status: 'Break',
    truck: 'Truck TR-1136',
    truckState: 'break',
    currentLoad: null,
    eta: { time: '10:55' },
  },
  {
    id: 'DR-1135',
    name: 'Mia Walker',
    avatarUrl: 'https://randomuser.me/api/portraits/women/57.jpg',
    status: 'On Duty',
    truck: 'Truck TR-1144',
    truckState: 'active',
    currentLoad: 'Load #LD-11890',
    eta: { time: '20:05', state: 'On time' },
  },
];
