export const AI_PROCESSING_QUEUE = "ai-processing";
export const DOCUMENT_PROCESSING_QUEUE = "document-processing";
export const EMAIL_NOTIFICATIONS_QUEUE = "email-notifications";

export const REDIS_CONNECTION = "REDIS_CONNECTION";
export const AI_PROCESSING_QUEUE_TOKEN = "AI_PROCESSING_QUEUE_TOKEN";
export const DOCUMENT_PROCESSING_QUEUE_TOKEN =
  "DOCUMENT_PROCESSING_QUEUE_TOKEN";
export const EMAIL_NOTIFICATIONS_QUEUE_TOKEN =
  "EMAIL_NOTIFICATIONS_QUEUE_TOKEN";
