export type AiLogStatus = "Failed" | "Success";

export type AiLog = {
  id: string;
  time: string;
  model: string;
  operation: string;
  status: AiLogStatus;
  latency: string;
  tokens: string;
  tokenDetail: string;
  cost: string;
  user: string;
  initials: string;
  source: "Mobile" | "Web";
  linkedType: string;
  linkedId: string;
  linkedTitle: string;
  route?: string;
  prompt: string;
  response: string;
};

const basePrompt =
  "Show me delayed loads in the Midwest from yesterday and suggest the next actions.";
const baseResponse =
  "Found 6 delayed loads in the Midwest on May 27, 2025. Severe storms and an I-94 accident caused the largest delays.";

export const aiLogs: AiLog[] = [
  [
    "log-1",
    "May 28, 09:15:42",
    "GPT-4.1",
    "AI Assistant (chat)",
    "Success",
    "2.12s",
    "2,145",
    "1,245 prompt / 900 completion",
    "$0.032",
    "Alex Dispatcher",
    "AD",
    "Web",
    "Load",
    "LD-78291",
    "Equipment parts",
    "Chicago, IL → Detroit, MI",
  ],
  [
    "log-2",
    "May 28, 09:14:01",
    "GPT-4.1",
    "Document extraction",
    "Success",
    "4.32s",
    "6,842",
    "6,114 prompt / 728 completion",
    "$0.102",
    "Alex Dispatcher",
    "AD",
    "Web",
    "Document",
    "DOC-5562",
    "Bill of lading",
  ],
  [
    "log-3",
    "May 28, 09:12:37",
    "GPT-4.1",
    "Delay analysis",
    "Success",
    "3.01s",
    "3,210",
    "2,610 prompt / 600 completion",
    "$0.048",
    "Sarah Davis",
    "SD",
    "Web",
    "Incident",
    "INC-2291",
    "Late delivery risk",
  ],
  [
    "log-4",
    "May 28, 09:10:11",
    "GPT-4.1",
    "Route optimization",
    "Success",
    "5.21s",
    "8,912",
    "7,806 prompt / 1,106 completion",
    "$0.134",
    "Alex Dispatcher",
    "AD",
    "Web",
    "Load",
    "LD-10456",
    "Retail goods",
    "Dallas, TX → Phoenix, AZ",
  ],
  [
    "log-5",
    "May 28, 09:08:55",
    "GPT-3.5 Turbo",
    "AI Assistant (chat)",
    "Success",
    "1.45s",
    "1,102",
    "702 prompt / 400 completion",
    "$0.006",
    "Michael Wilson",
    "MW",
    "Mobile",
    "Driver",
    "TR-1042",
    "Driver support",
  ],
  [
    "log-6",
    "May 28, 09:07:33",
    "GPT-4.1",
    "Incident summary",
    "Success",
    "2.78s",
    "2,987",
    "2,301 prompt / 686 completion",
    "$0.045",
    "Sarah Davis",
    "SD",
    "Web",
    "Incident",
    "INC-2291",
    "Late delivery risk",
  ],
  [
    "log-7",
    "May 28, 09:05:22",
    "GPT-4.1",
    "Document extraction",
    "Failed",
    "8.91s",
    "0",
    "0 prompt / 0 completion",
    "$0.000",
    "Alex Dispatcher",
    "AD",
    "Web",
    "Document",
    "DOC-5561",
    "Damaged scan",
  ],
  [
    "log-8",
    "May 28, 09:02:18",
    "GPT-4.1",
    "Suggested actions",
    "Success",
    "3.56s",
    "4,123",
    "3,411 prompt / 712 completion",
    "$0.062",
    "Emily Taylor",
    "ET",
    "Web",
    "Load",
    "LD-2156",
    "Automotive supplies",
  ],
  [
    "log-9",
    "May 28, 09:01:07",
    "GPT-3.5 Turbo",
    "Weather impact",
    "Success",
    "1.12s",
    "1,008",
    "688 prompt / 320 completion",
    "$0.004",
    "Michael Wilson",
    "MW",
    "Mobile",
    "Load",
    "LD-9901",
    "Fresh produce",
  ],
  [
    "log-10",
    "May 28, 08:59:44",
    "GPT-4.1",
    "Report generation",
    "Success",
    "6.34s",
    "9,456",
    "8,204 prompt / 1,252 completion",
    "$0.142",
    "Alex Dispatcher",
    "AD",
    "Web",
    "Report",
    "RPT-332",
    "Daily operations brief",
  ],
].map(
  ([
    id,
    time,
    model,
    operation,
    status,
    latency,
    tokens,
    tokenDetail,
    cost,
    user,
    initials,
    source,
    linkedType,
    linkedId,
    linkedTitle,
    route,
  ]) => ({
    id,
    time,
    model,
    operation,
    status,
    latency,
    tokens,
    tokenDetail,
    cost,
    user,
    initials,
    source,
    linkedType,
    linkedId,
    linkedTitle,
    route,
    prompt: basePrompt,
    response:
      status === "Failed"
        ? "The source document could not be parsed because the scan quality was too low."
        : baseResponse,
  }),
) as AiLog[];

export const metricData = [
  {
    title: "AI Requests",
    value: "18,392",
    change: "12.5%",
    direction: "up",
    favorable: true,
    color: "#0891b2",
    data: [18, 16, 21, 17, 14, 17, 23, 22],
  },
  {
    title: "Avg Latency",
    value: "2.34s",
    change: "8.1%",
    direction: "down",
    favorable: true,
    color: "#0f766e",
    data: [18, 22, 21, 19, 20, 17, 18, 23],
  },
  {
    title: "Errors",
    value: "37",
    change: "15.3%",
    direction: "up",
    favorable: false,
    color: "#dc2626",
    data: [6, 7, 14, 19, 12, 5, 5, 6],
  },
  {
    title: "Tokens Used",
    value: "4.2M",
    change: "9.7%",
    direction: "up",
    favorable: false,
    color: "#5b5fc7",
    data: [17, 14, 21, 18, 14, 18, 23, 20],
  },
  {
    title: "Estimated Cost",
    value: "$68.42",
    change: "11.2%",
    direction: "up",
    favorable: false,
    color: "#d97706",
    data: [14, 12, 20, 9, 13, 12, 12, 12],
  },
] as const;
