import {
  AlertTriangle,
  Bot,
  CloudRain,
  FileText,
  Megaphone,
  Settings,
  Truck,
  UserRound,
  UserRoundX,
} from "lucide-react";

export const notifications = [
  {
    id: 1,
    type: "Loads",
    title: "Delay detected on Load LD-78291",
    detail: "ETA updated: now May 28, 16:30",
    time: "2 min ago",
    icon: Truck,
    tone: "danger",
    unread: true,
  },
  {
    id: 2,
    type: "Drivers",
    title: "Driver John Smith assigned to Load LD-10456",
    detail: "Dallas, TX → Houston, TX",
    time: "15 min ago",
    icon: UserRound,
    tone: "blue",
    unread: false,
  },
  {
    id: 3,
    type: "Incidents",
    title: "Incident INC-2291 status changed to Investigating",
    detail: "I-94, Michigan",
    time: "32 min ago",
    icon: AlertTriangle,
    tone: "warning",
    unread: false,
  },
  {
    id: 4,
    type: "Documents",
    title: "Document extracted from BOL_78291_2025-05-28.pdf",
    detail: "Bill of Lading · 32 fields extracted",
    time: "1 hr ago",
    icon: FileText,
    tone: "teal",
    unread: false,
  },
  {
    id: 5,
    type: "System",
    title: "Weather alert for route on Load LD-2156",
    detail: "Severe storms expected in Atlanta, GA",
    time: "2 hrs ago",
    icon: CloudRain,
    tone: "blue",
    unread: false,
  },
  {
    id: 6,
    type: "Loads",
    title: "Load LD-9901 delivered",
    detail: "Los Angeles, CA → Phoenix, AZ",
    time: "3 hrs ago",
    icon: Truck,
    tone: "teal",
    unread: false,
  },
  {
    id: 7,
    type: "AI & Reports",
    title: "AI report generated",
    detail: "Daily operations summary is ready",
    time: "5 hrs ago",
    icon: Bot,
    tone: "violet",
    unread: false,
  },
  {
    id: 8,
    type: "Drivers",
    title: "Driver Michael Wilson unavailable",
    detail: "May 28, 14:00 – 22:00",
    time: "Yesterday",
    icon: UserRoundX,
    tone: "danger",
    unread: false,
  },
] as const;

export const preferenceItems = [
  {
    id: "loads",
    label: "Loads",
    description: "Updates on load status, assignments and delays",
    icon: Truck,
    enabled: true,
  },
  {
    id: "drivers",
    label: "Drivers",
    description: "Driver assignments, availability and updates",
    icon: UserRound,
    enabled: true,
  },
  {
    id: "incidents",
    label: "Incidents",
    description: "Incident alerts and status changes",
    icon: AlertTriangle,
    enabled: true,
  },
  {
    id: "documents",
    label: "Documents",
    description: "Document uploads and extraction results",
    icon: FileText,
    enabled: false,
  },
  {
    id: "ai",
    label: "AI & Reports",
    description: "AI suggestions, reports and insights",
    icon: Bot,
    enabled: true,
  },
  {
    id: "system",
    label: "System",
    description: "System updates and maintenance",
    icon: Settings,
    enabled: false,
  },
  {
    id: "marketing",
    label: "Marketing",
    description: "Product updates and tips",
    icon: Megaphone,
    enabled: false,
  },
] as const;
