import type { Incident } from "./types";

export const mockIncidents: Incident[] = [
  {
    id: "INC-128",
    title: "Accident detected",
    location: "I-94, Michigan",
    priority: "High",
    status: "Open",
    driver: { name: "John Smith", truck: "TR-1042", avatarUrl: "" },
    load: "LD-78291",
    occurredAt: { primary: "09:42", secondary: "May 28" },
    updatedAt: "2 min ago",
  },
  {
    id: "INC-127",
    title: "Delay risk",
    location: "Dallas, TX",
    priority: "Medium",
    status: "Investigating",
    driver: { name: "Sarah Davis", truck: "TR-1022", avatarUrl: "" },
    load: "LD-10456",
    occurredAt: { primary: "08:15", secondary: "May 28" },
    updatedAt: "15 min ago",
  },
  {
    id: "INC-126",
    title: "Maintenance alert",
    location: "Truck TR-1042",
    priority: "Low",
    status: "Open",
    driver: { name: "John Smith", truck: "TR-1042", avatarUrl: "" },
    load: null,
    occurredAt: { primary: "07:58", secondary: "May 28" },
    updatedAt: "1 hr ago",
  },
  {
    id: "INC-125",
    title: "Route deviation",
    location: "I-80, Ohio",
    priority: "Medium",
    status: "Monitoring",
    driver: { name: "Robert Brown", truck: "TR-1055", avatarUrl: "" },
    load: "LD-2156",
    occurredAt: { primary: "06:30", secondary: "May 28" },
    updatedAt: "2 hr ago",
  },
  {
    id: "INC-124",
    title: "Document issue",
    location: "POD missing",
    priority: "Low",
    status: "Resolved",
    driver: { name: "Emily Taylor", truck: "TR-1011", avatarUrl: "" },
    load: "LD-9901",
    occurredAt: { primary: "Yesterday", secondary: "19:20" },
    updatedAt: "1 day ago",
  },
  {
    id: "INC-123",
    title: "Weather alert",
    location: "Severe storms",
    priority: "Low",
    status: "Closed",
    driver: null,
    load: null,
    occurredAt: { primary: "Yesterday", secondary: "16:45" },
    updatedAt: "1 day ago",
  },
  {
    id: "INC-122",
    title: "Driver fatigue risk",
    location: "Hours limit",
    priority: "High",
    status: "Open",
    driver: { name: "Michael Wilson", truck: "TR-1066", avatarUrl: "" },
    load: "LD-2156",
    occurredAt: { primary: "May 27", secondary: "23:10" },
    updatedAt: "1 day ago",
  },
  {
    id: "INC-121",
    title: "Load temperature",
    location: "Reefer alert",
    priority: "Medium",
    status: "Monitoring",
    driver: { name: "David Lee", truck: "TR-1088", avatarUrl: "" },
    load: "LD-3321",
    occurredAt: { primary: "May 27", secondary: "14:05" },
    updatedAt: "2 days ago",
  },
];
